# Generated by Django 5.2.11 on 2026-04-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='ID компании'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('client_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=30)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='users.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed_lost', 'Closed Lost')], db_index=True, default='new', max_length=30)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='users.lead'),
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='users.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_id', 'status'], name='users_lead_company_2820d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_id', 'responsible'], name='users_lead_company_394c60_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company_id', 'stage'], name='users_deal_company_037cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company_id', 'responsible'], name='users_deal_company_58ef11_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company_id', 'created_at'], name='users_deal_company_0e7d48_idx'),
        ),
    ]
