# Generated by Django 6.0.4 on 2026-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_move_crm_models_to_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='ID компании'),
        ),
    ]
